/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117753-g9ec042c1aa-20241111"
#endif /* AVUTIL_FFVERSION_H */
